FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go mod tidy && go build -o /app/processor ./cmd

FROM alpine:latest

COPY --from=builder /app/processor /app/processor

COPY config/local.yaml /etc/myapp/config.yaml

EXPOSE 9300

WORKDIR /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["./processor"]