FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .
RUN go mod tidy && go build -o collector ./cmd

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/collector .

COPY config/local.yaml .

EXPOSE 9200

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["./collector"]
