global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'myproducer'
    static_configs:
      - targets: ['myproducer:9100']

  - job_name: 'collector'
    static_configs:
      - targets: ['collector:9200']

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:9200']